<a href="https://colab.research.google.com/github/gaganmathur99/Recommendation-System/blob/master/Movie_Recommendation_using_Correlation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
url = 'https://raw.githubusercontent.com/gaganmathur99/Recommendation-System/master/movies.csv'

In [0]:
movies = pd.read_csv(url)

In [17]:
movies.head()

   movieId  ...                                       genres
0        1  ...  Adventure|Animation|Children|Comedy|Fantasy
1        2  ...                   Adventure|Children|Fantasy
2        3  ...                               Comedy|Romance
3        4  ...                         Comedy|Drama|Romance
4        5  ...                                       Comedy

[5 rows x 3 columns]

In [0]:
url = 'https://raw.githubusercontent.com/gaganmathur99/Recommendation-System/master/ratings.csv'

In [0]:
ratings = pd.read_csv(url)

In [20]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [0]:
ratings=ratings.merge(movies,on='movieId',how='left')

In [22]:
ratings.head()

   userId  ...                                       genres
0       1  ...  Adventure|Animation|Children|Comedy|Fantasy
1       1  ...                               Comedy|Romance
2       1  ...                        Action|Crime|Thriller
3       1  ...                             Mystery|Thriller
4       1  ...                       Crime|Mystery|Thriller

[5 rows x 6 columns]

In [0]:
Avg_ratings=pd.DataFrame(ratings.groupby('title')['rating'].mean())

In [25]:
Avg_ratings.head(10)

                                           rating
title
'71 (2014)                               4.000000
'Hellboy': The Seeds of Creation (2004)  4.000000
'Round Midnight (1986)                   3.500000
'Salem's Lot (2004)                      5.000000
'Til There Was You (1997)                4.000000
'Tis the Season for Love (2015)          1.500000
'burbs, The (1989)                       3.176471
'night Mother (1986)                     3.000000
(500) Days of Summer (2009)              3.666667
*batteries not included (1987)           3.285714

In [0]:
Avg_ratings['Total Ratings']=pd.DataFrame(ratings.groupby('title')['rating'].count())

In [29]:
Avg_ratings.head(10)

                                           rating  Total Ratings
title
'71 (2014)                               4.000000              1
'Hellboy': The Seeds of Creation (2004)  4.000000              1
'Round Midnight (1986)                   3.500000              2
'Salem's Lot (2004)                      5.000000              1
'Til There Was You (1997)                4.000000              2
'Tis the Season for Love (2015)          1.500000              1
'burbs, The (1989)                       3.176471             17
'night Mother (1986)                     3.000000              1
(500) Days of Summer (2009)              3.666667             42
*batteries not included (1987)           3.285714              7

In [0]:
movie_user=ratings.pivot_table(index='userId',columns='title',values='rating')

In [32]:
movie_user.head(20)

title   '71 (2014)  ...  À nous la liberté (Freedom for Us) (1931)
userId              ...
1              NaN  ...                                        NaN
2              NaN  ...                                        NaN
3              NaN  ...                                        NaN
4              NaN  ...                                        NaN
5              NaN  ...                                        NaN
6              NaN  ...                                        NaN
7              NaN  ...                                        NaN
8              NaN  ...                                        NaN
9              NaN  ...                                        NaN
10             NaN  ...                                        NaN
11             NaN  ...                                        NaN
12             NaN  ...                                        NaN
13             NaN  ...                                        NaN
14             NaN  ...                                        NaN
15             NaN  ...                                        NaN
16             NaN  ...                                        NaN
17             NaN  ...                                        NaN
18             NaN  ...                                        NaN
19             NaN  ...                                        NaN
20             NaN  ...                                        NaN

[20 rows x 9719 columns]

In [59]:
correlations = movie_user.corrwith(movie_user['Jumanji: Welcome to the Jungle (2017)'])

/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:2526: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:2455: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)

In [61]:
correlations.head(10)

title
'71 (2014)                                NaN
'Hellboy': The Seeds of Creation (2004)   NaN
'Round Midnight (1986)                    NaN
'Salem's Lot (2004)                       NaN
'Til There Was You (1997)                 NaN
'Tis the Season for Love (2015)           NaN
'burbs, The (1989)                        NaN
'night Mother (1986)                      NaN
(500) Days of Summer (2009)               NaN
*batteries not included (1987)            NaN
dtype: float64

In [0]:
recommendation=pd.DataFrame(correlations,columns=['Correlation'])

In [0]:
recommendation.dropna(inplace=True)

In [0]:
recommendation=recommendation.join(Avg_ratings['Total Ratings'])

In [65]:
recommendation.head()

                                   Correlation  Total Ratings
title
300 (2007)                           -0.866025             80
3:10 to Yuma (2007)                   0.000000             25
50 First Dates (2004)                -0.802955             47
Ace Ventura: Pet Detective (1994)     1.000000            161
Addams Family Values (1993)          -1.000000             84

In [0]:
recc=recommendation[recommendation['Total Ratings']>100].sort_values('Correlation',ascending=False).reset_index()

In [0]:
recc=recc.merge(movies,on='title',how='left')

In [68]:
recc.head(10)

                                            title  ...                                             genres
0               Ace Ventura: Pet Detective (1994)  ...                                             Comedy
1                                     Heat (1995)  ...                              Action|Crime|Thriller
2                Men in Black (a.k.a. MIB) (1997)  ...                               Action|Comedy|Sci-Fi
3                                  Jumanji (1995)  ...                         Adventure|Children|Fantasy
4                                    Shrek (2001)  ...  Adventure|Animation|Children|Comedy|Fantasy|Ro...
5                                    X-Men (2000)  ...                            Action|Adventure|Sci-Fi
6                             Donnie Darko (2001)  ...                      Drama|Mystery|Sci-Fi|Thriller
7  Harry Potter and the Chamber of Secrets (2002)  ...                                  Adventure|Fantasy
8                            Batman Begins (2005)  ...                                  Action|Crime|IMAX
9                       Back to the Future (1985)  ...                            Adventure|Comedy|Sci-Fi

[10 rows x 5 columns]